import Foundation

// MARK: - Idiomas
struct LanguageCards {
    // Inglés - Español
    static let inglesEspanol: [(front: String, back: String)] = [
        ("Hello", "Hola"),
        ("Goodbye", "Adiós"),
        ("Please", "Por favor"),
        ("Thank you", "Gracias"),
        ("Sorry", "Lo siento"),
        ("Yes", "Sí"),
        ("No", "No"),
        ("Good morning", "Buenos días"),
        ("Good night", "Buenas noches"),
        ("How are you?", "¿Cómo estás?"),
        ("I love you", "Te quiero"),
        ("Water", "Agua"),
        ("Food", "Comida"),
        ("House", "Casa"),
        ("Car", "Coche"),
        ("Book", "Libro"),
        ("Time", "Tiempo/Hora"),
        ("Money", "Dinero"),
        ("Work", "Trabajo"),
        ("Family", "Familia"),
        ("Friend", "Amigo"),
        ("Dog", "Perro"),
        ("Cat", "Gato"),
        ("Day", "Día"),
        ("Night", "Noche"),
        ("Sun", "Sol"),
        ("Moon", "Luna"),
        ("Sea", "Mar"),
        ("Mountain", "Montaña"),
        ("To eat", "Comer"),
        ("To drink", "Beber"),
        ("To speak", "Hablar"),
        ("To write", "Escribir"),
        ("To read", "Leer"),
        ("To walk", "Caminar"),
        ("To run", "Correr"),
    ]
    
    // Gallego - Español
    static let galegoEspanol: [(front: String, back: String)] = [
        ("Ola", "Hola"),
        ("Adeus", "Adiós"),
        ("Grazas", "Gracias"),
        ("Por favor", "Por favor"),
        ("Si", "Sí"),
        ("Non", "No"),
        ("Bos días", "Buenos días"),
        ("Boas noites", "Buenas noches"),
        ("Como estás?", "¿Cómo estás?"),
        ("Querído", "Querido"),
        ("Auga", "Augua"),
        ("Comida", "Comida"),
        ("Casa", "Casa"),
        ("Coche", "Coche"),
        ("Libro", "Libro"),
        ("Tempo", "Tiempo"),
        ("Dinheiro", "Dinero"),
        ("Traballo", "Trabajo"),
        ("Familia", "Familia"),
        ("Amigo", "Amigo"),
        ("Can", "Perro"),
        ("Gato", "Gato"),
        ("Día", "Día"),
        ("Noite", "Noite"),
        ("Sol", "Sol"),
        ("Lúa", "Luna"),
        ("Mar", "Mar"),
        ("Monte", "Montaña"),
        ("Comer", "Comer"),
        ("Beber", "Beber"),
        ("Falar", "Hablar"),
        ("Escribir", "Escribir"),
        ("Ler", "Ler"),
        ("Andar", "Caminar"),
        ("Correr", "Correr"),
    ]
    
    // Francés - Español
    static let francesEspanol: [(front: String, back: String)] = [
        ("Bonjour", "Hola/Buenos días"),
        ("Au revoir", "Adiós"),
        ("Merci", "Gracias"),
        ("S'il vous plaît", "Por favor"),
        ("Oui", "Sí"),
        ("Non", "No"),
        ("Bonsoir", "Buenas tardes/noches"),
        ("Comment allez-vous?", "¿Cómo está usted?"),
        ("Je t'aime", "Te quiero"),
        ("L'eau", "El agua"),
        ("La nourriture", "La comida"),
        ("La maison", "La casa"),
        ("La voiture", "El coche"),
        ("Le livre", "El libro"),
        ("Le temps", "El tiempo"),
        ("L'argent", "El dinero"),
        ("Le travail", "El trabajo"),
        ("La famille", "La familia"),
        ("L'ami", "El amigo"),
        ("Le chien", "El perro"),
        ("Le chat", "El gato"),
        ("Le jour", "El día"),
        ("La nuit", "La noche"),
        ("Le soleil", "El sol"),
        ("La lune", "La luna"),
    ]
    
    // Alemán - Español
    static let alemanEspanol: [(front: String, back: String)] = [
        ("Hallo", "Hola"),
        ("Auf Wiedersehen", "Adiós"),
        ("Danke", "Gracias"),
        ("Bitte", "Por favor"),
        ("Ja", "Sí"),
        ("Nein", "No"),
        ("Guten Morgen", "Buenos días"),
        ("Gute Nacht", "Buenas noches"),
        ("Wie geht es Ihnen?", "¿Cómo está usted?"),
        ("Ich liebe dich", "Te quiero"),
        ("Das Wasser", "El agua"),
        ("Das Essen", "La comida"),
        ("Das Haus", "La casa"),
        ("Das Auto", "El coche"),
        ("Das Buch", "El libro"),
        ("Die Zeit", "El tiempo"),
        ("Das Geld", "El dinero"),
        ("Die Arbeit", "El trabajo"),
        ("Die Familie", "La familia"),
        ("Der Freund", "El amigo"),
        ("Der Hund", "El perro"),
        ("Die Katze", "El gato"),
        ("Der Tag", "El día"),
        ("Die Nacht", "La noche"),
        ("Die Sonne", "El sol"),
        ("Der Mond", "La luna"),
    ]
}
